// 기본적인 웹 페이지의 골격
import Link from "next/link";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Web tutorial",
  description: "Generated by Woohyun",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
          {/* Link 컴포넌트를 사용함으로써
          1. 페이지 리로딩이 없어졌다. 
          2. 방문한 페이지를 다운로드 받지 않는다. 
          3. 미리 페이지를 다운로드 한다.(마우스를 올리는 순간 백그라운드에서 다운로드)  
          👉🏻 즉, Link는 Next.js에서 SPA를 쉽게 구현하도록 도와주는 도구이다 !
          */}
        </h1>
        <ol>
          <li>
            <Link href="/read/1">html</Link>
          </li>
          <li>
            <Link href="/read/2">css</Link>
          </li>
        </ol>
        {children}
        <ul>
          <li>
            <Link href="/create">create</Link>
          </li>
          <li>
            <Link href="/update/id">update</Link>
          </li>
          <li>
            <button>delete</button>
          </li>
        </ul>
      </body>
    </html>
  );
}
